[project]
name = "fastapi-websocket-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.121.3",
    "websockets>=15.0.1",
]
